module.exports = [
  {
    email: "bartek5412@gmail.com",
    password: "123456789",
    name: "Leader",
    role: "leader",
    daysAvailable: 26,
    daysPerYear: 26,
  },
  {
    email: "a.fogel@fundacjacp.org",
    password: "RANDOM",
    name: "Agata Fogel",
    role: "employee",
    daysAvailable: 26,
    daysPerYear: 26,
  },
  {
    email: "a.serba@fundacjacp.org",
    password: "RANDOM",
    name: "Anna Serba",
    role: "employee",
    daysAvailable: 26,
    daysPerYear: 26,
  },
  {
    email: "a.szmyd@fundacjacp.org",
    password: "RANDOM",
    name: "Anna Szmyd",
    role: "employee",
    daysAvailable: 26,
    daysPerYear: 26,
  },
  {
    email: "b.malachowska@fundacjacp.org",
    password: "RANDOM",
    name: "Beata Małachowska",
    role: "employee",
    daysAvailable: 26,
    daysPerYear: 26,
  },
  {
    email: "d.mitus@fundacjacp.org",
    password: "RANDOM",
    name: "Daria Mituś",
    role: "employee",
    daysAvailable: 26,
    daysPerYear: 26,
  },
  {
    email: "d.kolkowska@fundacjacp.org",
    password: "RANDOM",
    name: "Dorota Kołkowska",
    role: "employee",
    daysAvailable: 26,
    daysPerYear: 26,
  },
  {
    email: "g.podruczny@fundacjacp.org",
    password: "RANDOM",
    name: "Grzegorz Podruczny",
    role: "employee",
    daysAvailable: 26,
    daysPerYear: 26,
  },
  {
    email: "j.strzalkowska@fundacjacp.org",
    password: "RANDOM",
    name: "Joanna Strzałkowska",
    role: "employee",
    daysAvailable: 26,
    daysPerYear: 26,
  },
  {
    email: "k.malicz@fundacjacp.org",
    password: "RANDOM",
    name: "Kamila Malicz",
    role: "employee",
    daysAvailable: 26,
    daysPerYear: 26,
  },
  {
    email: "k.dreszer@fundacjacp.org",
    password: "RANDOM",
    name: "Karolina Dreszer",
    role: "employee",
    daysAvailable: 26,
    daysPerYear: 26,
  },
  {
    email: "k.osinska@fundacjacp.org",
    password: "RANDOM",
    name: "Katarzyna Osińska",
    role: "employee",
    daysAvailable: 26,
    daysPerYear: 26,
  },
  {
    email: "k.szewielinska@fundacjacp.org",
    password: "RANDOM",
    name: "Katarzyna Szewielińska",
    role: "employee",
    daysAvailable: 26,
    daysPerYear: 26,
  },
  {
    email: "m.tokarska@fundacjacp.org",
    password: "RANDOM",
    name: "Magdalena Tokarska",
    role: "employee",
    daysAvailable: 26,
    daysPerYear: 26,
  },
  {
    email: "m.buchaniec-kindra@fundacjacp.org",
    password: "RANDOM",
    name: "Marta Buchaniec-Kindra",
    role: "employee",
    daysAvailable: 26,
    daysPerYear: 26,
  },
  {
    email: "m.stachowska@fundacjacp.org",
    password: "RANDOM",
    name: "Marta Stachowska",
    role: "employee",
    daysAvailable: 26,
    daysPerYear: 26,
  },
  {
    email: "m.michalska@fundacjacp.org",
    password: "RANDOM",
    name: "Monika Michalska",
    role: "employee",
    daysAvailable: 26,
    daysPerYear: 26,
  },
  {
    email: "n.domina@fundacjacp.org",
    password: "RANDOM",
    name: "Natalia Domina",
    role: "employee",
    daysAvailable: 26,
    daysPerYear: 26,
  },
  {
    email: "p.stefanicki@fundacjacp.org",
    password: "RANDOM",
    name: "Paweł Stefanicki",
    role: "employee",
    daysAvailable: 26,
    daysPerYear: 26,
  },
  {
    email: "s.kostrzewa@fundacjacp.org",
    password: "RANDOM",
    name: "Sylwia Kostrzewa",
    role: "employee",
    daysAvailable: 26,
    daysPerYear: 26,
  },
  {
    email: "t.testowy@fundacjacp.org",
    password: "RANDOM",
    name: "Testek Testowy",
    role: "employee",
    daysAvailable: 26,
    daysPerYear: 26,
  },
  {
    email: "w.mazurek@fundacjacp.org",
    password: "RANDOM",
    name: "Wioletta Mazurek",
    role: "employee",
    daysAvailable: 26,
    daysPerYear: 26,
  },
  {
    email: "l.krzyskow@fundacjacp.org",
    password: "RANDOM",
    name: "Łukasz Krzyśków",
    role: "employee",
    daysAvailable: 26,
    daysPerYear: 26,
  },
];
