module.exports = [

  {
    email: "ewa.lider@example.com",
    password: "ewa1234",
    name: "Ewa Lider",
    role: "leader",
    daysAvailable: 26,
    daysPerYear: 26,
  },
  {
    email: "jan.nowak@example.com",
    password: "RANDOM",
    name: "Jan Nowak",
    role: "employee",
    leaderEmail: "bartek5412@gmail.com",
    daysAvailable: 24,
    daysPerYear: 26,
  },
  {
    email: "anna.kowalska@example.com",
    password: "RANDOM",
    name: "Anna Kowalska",
    role: "employee",
    leaderEmail: "bartek5412@gmail.com",
    daysAvailable: 20,
    daysPerYear: 26,
  },
  {
    email: "piotr.mazur@example.com",
    password: "RANDOM",
    name: "Piotr Mazur",
    role: "employee",
    leaderEmail: "ewa.lider@example.com",
    daysAvailable: 26,
    daysPerYear: 26,
  },
  {
    email: "demo.user@example.com",
    password: "demo1234",
    name: "Demo User",
    role: "employee",
    leaderEmail: "ewa.lider@example.com",
    daysAvailable: 15,
    daysPerYear: 26,
  },
];
