name: Deploy manually

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH Key
        run: |
          mkdir -p ~/.ssh/
          # Wgrywamy klucz z sekretów do pliku (tak jak masz lokalnie ./vps_key)
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          # Dodajemy serwer do znanych hostów, żeby nie pytał "Are you sure?"
          ssh-keyscan -p 48624 -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Copy files via SCP (Native)
        run: |
          # Kopiujemy pliki używając systemowego SCP (tak jak Ty lokalnie)
          # Flaga -P (duże P) służy do portu w scp, w ssh jest małe -p
          scp -P 48624 -i ~/.ssh/id_rsa -r docker-compose.prod.yml prisma/ ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }}:/opt/urlopy-v2

      - name: Deploy via SSH (Native)
        run: |
          ssh -p 48624 -i ~/.ssh/id_rsa ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} << 'EOF'
            cd /opt/urlopy-v2
            
            # Tutaj zwykłe komendy basha
            docker-compose -f docker-compose.prod.yml down || true
            docker-compose -f docker-compose.prod.yml build
            docker-compose -f docker-compose.prod.yml up -d
            
            docker image prune -f
          EOF
